apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: meshify-prototyping-integration
  description: The prototyping and integration organization
  links:
    - url: http://www.meshify.com.com/
      title: Website
    - url: https://conf-4.carbon.meshify.co
      title: Conf-4 Staging Tenant
spec:
  type: organization
  profile:
    displayName: Meshify P&I
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
